// Assembly DSkin, Version 16.4.2.6

[assembly: System.Reflection.AssemblyTrademark("DSkin界面库  http://www.dskin.cn/")]
[assembly: System.Reflection.AssemblyProduct("DSkin界面库  http://www.dskin.cn/")]
[assembly: System.Reflection.AssemblyDescription("DSkin界面库  http://www.dskin.cn/")]
[assembly: System.Reflection.AssemblyCompany("DSkin界面库  http://www.dskin.cn/")]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 DSkin界面库   http://www.dskin.cn/")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyTitle("DSkin界面库   http://www.dskin.cn/")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("af92b888-50bd-4af8-9b73-d98bfdaa473b")]
[assembly: System.Reflection.AssemblyFileVersion("16.4.2.6")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

